### ISSUE TITLE
Array as attribute in struct

### ISSUE THREAD

**Issue by LeoNavel** [tris-foundation/reflection#1]
Can not construct struct when it has array value

```swift
struct Post {
    var comments: [Comment] = []
}
```

**Comment by tonyfreeman** [comment]
Hi! Sorry for the delay. 
Yeah, you can't construct arrays with the current version. It was initially written for constructing simple flat structs. Please let me know if you still interested in this feature, i'll look into it.

**Comment by LeoNavel** [comment]
Hi! No problem, I migrate my code to swift 4 and `Codable` protocol so I'm fine :) thanks for responding.
